import { ArrowRight, Bell, ChevronRight, CircleCheck, Clock3, FileText, Package, Plus, WalletCards } from "lucide-react";
import { Link } from "wouter";

const quotes = [
  { ref: "WR-2026-00125", product: "Cotton Oversized T-Shirt + 1 more", date: "Aug 12, 2026", status: "Quoted", tone: "green", action: "Review quotation" },
  { ref: "WR-2026-00118", product: "Premium Fleece Hoodie", date: "Aug 09, 2026", status: "Pending", tone: "amber", action: "View request" },
  { ref: "WR-2026-00110", product: "Classic Pique Polo Shirt", date: "Jul 22, 2026", status: "Invoiced", tone: "blue", action: "View invoice" },
];

function SideNav(){return <aside className="workspace-sidebar"><Link href="/" className="workspace-logo"><span className="brand-mark">C</span><span>CHADREY<small>WHOLESALE</small></span></Link><span className="sidebar-label">WORKSPACE</span><Link className="sidebar-link active" href="/dashboard"><CircleCheck size={16}/> Overview</Link><Link className="sidebar-link" href="/dashboard"><FileText size={16}/> My quotes <b>3</b></Link><Link className="sidebar-link" href="/dashboard"><WalletCards size={16}/> Invoices</Link><Link className="sidebar-link" href="/dashboard"><Package size={16}/> Orders</Link><span className="sidebar-label">ACCOUNT</span><Link className="sidebar-link" href="/dashboard">Addresses</Link><Link className="sidebar-link" href="/dashboard">Account settings</Link><div className="sidebar-bottom"><Link className="sidebar-link" href="/">← Back to store</Link></div></aside>}

export default function CustomerDashboard(){return <div className="workspace"><SideNav/><main className="workspace-main"><header className="workspace-header"><div><span className="eyebrow">CUSTOMER WORKSPACE</span><h1>Good morning, Alex.</h1><p>Here is the latest on your sourcing activity.</p></div><div className="workspace-header-actions"><button className="icon-button"><Bell size={17}/><i/></button><span className="avatar">AB</span></div></header><section className="dashboard-grid"><div className="summary-card summary-highlight"><span className="summary-icon"><FileText size={17}/></span><span>Open quote requests</span><strong>3</strong><small>2 awaiting your action</small></div><div className="summary-card"><span className="summary-icon"><Clock3 size={17}/></span><span>Awaiting quotation</span><strong>1</strong><small>Last updated 2h ago</small></div><div className="summary-card"><span className="summary-icon"><Package size={17}/></span><span>Orders in progress</span><strong>1</strong><small>Estimated delivery Aug 28</small></div></section><div className="workspace-columns"><section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR ACTIVITY</span><h2>Recent requests</h2></div><Link href="/quote" className="button button-primary small"><Plus size={15}/> New request</Link></div><div className="quote-table">{quotes.map(q=><div className="quote-row" key={q.ref}><div className={`status-symbol ${q.tone}`}><FileText size={17}/></div><div className="quote-row-main"><strong>{q.ref}</strong><span>{q.product}</span><small>{q.date}</small></div><div className={`status-pill ${q.tone}`}>{q.status}</div><Link href="/dashboard" className="row-action">{q.action}<ChevronRight size={15}/></Link></div>)}</div><Link href="/dashboard" className="panel-footer">View all requests <ArrowRight size={15}/></Link></section><section className="workspace-panel notification-panel"><div className="panel-heading"><div><span className="eyebrow">NOTIFICATIONS</span><h2>Keep moving</h2></div><span className="unread-count">2 new</span></div><div className="notification-item"><span className="notification-dot green"/><div><strong>Your quotation is ready to review</strong><p>WR-2026-00125 · 32 minutes ago</p></div></div><div className="notification-item"><span className="notification-dot amber"/><div><strong>We received your request</strong><p>WR-2026-00118 · Aug 9, 2026</p></div></div><div className="timeline-card"><span className="eyebrow">ORDER TRACKING</span><h3>Order WR-2026-00099</h3><div className="mini-timeline"><span className="done"/><span className="done"/><span className="current"/><span/><span/></div><div className="timeline-labels"><span>Paid</span><span>Processing</span><span>Shipping next</span></div><Link href="/dashboard" className="text-link">Track order <ArrowRight size={15}/></Link></div></section></div></main></div>}
