import { useState } from "react";
import { ArrowLeft, Check, Truck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

const steps=["Confirmed","Processing","Shipped","Delivered"];
export default function OrderTracking(){ const [location]=useLocation(); const orderId=Number(new URLSearchParams(location.split("?")[1]||"").get("orderId")||1); const { user, loading } = useAuth(); const orders=trpc.orders.mine.useQuery(undefined,{enabled:Boolean(user)}); const liveOrder=orders.data?.find(row=>row.order.id===orderId) ?? orders.data?.[0]; const [status,setStatus]=useState("processing"); const update=trpc.quotes.updateOrder.useMutation(); const effectiveStatus = liveOrder?.order.status ?? status; const current=Math.max(0,steps.findIndex(s=>s.toLowerCase()===effectiveStatus)); const save=async()=>{await update.mutateAsync({orderId,status:status as "processing"|"shipped"|"delivered"|"cancelled",trackingNumber:status==="shipped"?"CHAD-24018":undefined,carrier:status==="shipped"?"DHL":undefined})}; return <div className="app-shell"><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">C</span><span>CHADREY<small>WHOLESALE</small></span></Link><nav className="main-nav"><Link href="/dashboard">My Workspace</Link><Link href="/admin">Operations</Link></nav><span className="avatar">AB</span></header><main className="page-container narrow"><Link href="/dashboard" className="back-link"><ArrowLeft size={15}/> Back to workspace</Link><span className="eyebrow">ORDER TRACKING / {liveOrder?.order.id ?? orderId}</span><div className="document-heading"><div><h1>Your order is moving.</h1><p className="page-lede">A single view of confirmation, production, shipping, and delivery.</p></div><Truck size={30} color="var(--green)"/></div><section className="timeline-card large-timeline"><div className="timeline-track">{steps.map((step,index)=><div className={`timeline-step ${index<=current?"active":""}`} key={step}><span>{index<current?<Check size={14}/>:index+1}</span><strong>{step}</strong><small>{index<=current?index===current?"Current status":"Completed":"Upcoming"}</small></div>)}</div><div className="shipping-note"><span className="eyebrow">SHIPPING DETAILS</span><p>{liveOrder?.order.trackingNumber ? `${liveOrder.order.carrier || "Carrier"} · ${liveOrder.order.trackingNumber} · Tracking is available with the carrier.` : effectiveStatus==="shipped" ? "Carrier details are being prepared." : "Tracking will appear here once your order ships."}</p></div></section><section className="workspace-panel admin-control-card"><span className="eyebrow">ADMIN CONTROL</span><h2>Update fulfilment status</h2><div className="form-submit-row"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select><button className="button button-primary" onClick={save} disabled={update.isPending}>Save status</button></div></section></main></div> }
