import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, products, quoteRequests, quoteRequestItems, quotations, invoices, payments, orders, notifications, messages, type Product } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, role: values.role, lastSignedIn: values.lastSignedIn } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listProducts(): Promise<Product[]> { const db = await getDb(); if (!db) return []; return db.select().from(products).where(eq(products.isActive, 1)).orderBy(desc(products.createdAt)); }
export async function createQuote(input: { customerId: number; ref: string; notes?: string; items: Array<{ productId: number; quantity: number; color: string; size: string; packaging: string; customization: string }> }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(quoteRequests).values({ customerId: input.customerId, ref: input.ref, notes: input.notes ?? null, status: "pending" }); const quoteId = Number(result[0].insertId); if (input.items.length) await db.insert(quoteRequestItems).values(input.items.map(item => ({ ...item, quoteRequestId: quoteId }))); return quoteId; }
export async function listCustomerQuotes(customerId: number) { const db = await getDb(); if (!db) return []; return db.select().from(quoteRequests).where(eq(quoteRequests.customerId, customerId)).orderBy(desc(quoteRequests.createdAt)); }
export async function listAdminQuotes() { const db = await getDb(); if (!db) return []; return db.select().from(quoteRequests).orderBy(desc(quoteRequests.createdAt)); }
export async function markQuoteStatus(id: number, status: "quoted" | "accepted" | "declined" | "rejected" | "invoiced" | "paid" | "processing" | "shipped" | "delivered" | "cancelled", reason?: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(quoteRequests).set({ status, rejectionReason: reason ?? null }).where(eq(quoteRequests.id, id)); }
export async function createNotification(userId: number, type: string, title: string, body: string, refId?: string) { const db = await getDb(); if (!db) return; await db.insert(notifications).values({ userId, type, title, body, refId: refId ?? null }); }
export async function listNotifications(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(notifications).where(eq(notifications.userId, userId)).orderBy(desc(notifications.createdAt)); }
export async function createMessage(input: { quoteRequestId: number; senderId: number; body: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(messages).values(input); return Number(result[0].insertId); }

export async function getAdminCounts() { const db = await getDb(); if (!db) return { quoteRequests: 0, quotations: 0, invoices: 0, orders: 0 }; const [q, qt, inv, ord] = await Promise.all([db.select().from(quoteRequests), db.select().from(quotations), db.select().from(invoices), db.select().from(orders)]); return { quoteRequests: q.length, quotations: qt.length, invoices: inv.length, orders: ord.length }; }
export async function createQuotation(input: { quoteRequestId: number; issuedBy: number; subtotal: string; notes?: string; expiresAt?: Date }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(quotations).values({ quoteRequestId: input.quoteRequestId, issuedBy: input.issuedBy, subtotal: input.subtotal, notes: input.notes ?? null, expiresAt: input.expiresAt ?? null, status: "sent" }); await markQuoteStatus(input.quoteRequestId, "quoted"); return Number(result[0].insertId); }
export async function getQuotationForCustomer(quoteRequestId: number, customerId: number) { const db = await getDb(); if (!db) return undefined; const requests = await db.select().from(quoteRequests).where(eq(quoteRequests.id, quoteRequestId)).limit(1); if (!requests[0] || requests[0].customerId !== customerId) return undefined; const result = await db.select().from(quotations).where(eq(quotations.quoteRequestId, quoteRequestId)).orderBy(desc(quotations.issuedAt)).limit(1); return result[0]; }
export async function setQuotationStatus(quotationId: number, status: "accepted" | "declined") { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const rows = await db.select().from(quotations).where(eq(quotations.id, quotationId)).limit(1); if (!rows[0]) throw new Error("Quotation not found"); await db.update(quotations).set({ status }).where(eq(quotations.id, quotationId)); await markQuoteStatus(rows[0].quoteRequestId, status === "accepted" ? "accepted" : "declined"); }
export async function createInvoice(input: { quotationId: number; total: string; lineItems: unknown; dueDate: string; shippingCost?: string; tax?: string; paymentInstructions?: string }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const quotation = await db.select().from(quotations).where(eq(quotations.id, input.quotationId)).limit(1); if (!quotation[0] || quotation[0].status !== "accepted") throw new Error("Only accepted quotations can be invoiced"); const result = await db.insert(invoices).values({ quotationId: input.quotationId, total: input.total, lineItems: input.lineItems, dueDate: new Date(`${input.dueDate}T00:00:00Z`), shippingCost: input.shippingCost ?? "0", tax: input.tax ?? "0", paymentInstructions: input.paymentInstructions ?? null, status: "sent" }); await markQuoteStatus(quotation[0].quoteRequestId, "invoiced"); return Number(result[0].insertId); }
export async function getPaymentByTransaction(transactionId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(payments).where(eq(payments.transactionId, transactionId)).limit(1); return result[0]; }
export async function getInvoiceById(id: number) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(invoices).where(eq(invoices.id, id)).limit(1); return result[0]; }
export async function recordPayment(input: { invoiceId: number; provider: "flutterwave" | "stripe" | "bank_transfer"; transactionId: string; providerReference?: string; amount: string; currency: string; method?: string; rawPayload?: unknown }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(payments).values({ invoiceId: input.invoiceId, provider: input.provider, transactionId: input.transactionId, providerReference: input.providerReference ?? null, amount: input.amount, currency: input.currency, method: input.method ?? null, status: "successful", rawPayload: input.rawPayload ?? null }); return Number(result[0].insertId); }
export async function createPaidOrder(invoiceId: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = await db.select().from(orders).where(eq(orders.invoiceId, invoiceId)).limit(1); if (existing[0]) return existing[0].id; const result = await db.insert(orders).values({ invoiceId, status: "processing" }); await db.update(invoices).set({ status: "paid" }).where(eq(invoices.id, invoiceId)); return Number(result[0].insertId); }
export async function updateOrderStatus(orderId: number, status: "processing" | "shipped" | "delivered" | "cancelled", trackingNumber?: string, carrier?: string) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(orders).set({ status, trackingNumber: trackingNumber ?? null, carrier: carrier ?? null, shippedAt: status === "shipped" ? new Date() : undefined, deliveredAt: status === "delivered" ? new Date() : undefined }).where(eq(orders.id, orderId)); }
export async function listCustomerOrders(customerId: number) { const db = await getDb(); if (!db) return []; return db.select({ order: orders, invoice: invoices }).from(orders).innerJoin(invoices, eq(orders.invoiceId, invoices.id)).innerJoin(quotations, eq(invoices.quotationId, quotations.id)).innerJoin(quoteRequests, eq(quotations.quoteRequestId, quoteRequests.id)).where(eq(quoteRequests.customerId, customerId)).orderBy(desc(orders.createdAt)); }
export async function listAdminOrders() { const db = await getDb(); if (!db) return []; return db.select({ order: orders, invoice: invoices }).from(orders).innerJoin(invoices, eq(orders.invoiceId, invoices.id)).orderBy(desc(orders.createdAt)); }
